name: CD Pipeline

on:
  push:
    branches: [ master ]  # change to main if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Generate deployment package
        run: |
          zip -r address-book-app.zip \
            config controllers models routes \
            index.js package.json package-lock.json .env

      - name: Get Node.js version
        run: echo "VERSION=$(node -p \"require('./package.json').version\")" >> $GITHUB_ENV

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: ap-southeast-1
          application_name: ${{ secrets.EB_APP_NAME }}      # <- set exact value in repo secrets
          environment_name: ${{ secrets.EB_ENV_NAME }}      # <- set exact value in repo secrets
          version_label: v-${{ env.VERSION }}
          deployment_package: address-book-app.zip
